jwt:
  secretName: "supabase-jwt"

smtp:
  secretName: "supabase-smtp"

db:
  enabled: true
  image:
    repository:  quay.io/jland/supabase-postgres
    tag: "latest"
    pullPolicy: Always
  secretName: "supabase-db"
  persistence: 
    enabled: true
  storage:
      mountPath: /var/lib/pgsql/data
      size: 1Gi
      storageClass: gp3-csi
      annotations:
        helm.sh/resource-policy: "keep"

studio:
  image:
    repository:  docker.io/supabase/studio
    tag: 20240408-6bf3b81
  environment:
    SUPABASE_URL: http://supabase-kong:8000
    SUPABASE_REST_URL: http://supabase-kong:8000/rest/v1/
    STUDIO_PG_META_URL: http://supabase-kong:8000/pg
    # TBD


auth:
  image:
    repository: public.ecr.aws/supabase/gotrue
    tag: v2.40.1 # Trying out this tag
    # tag: v2.132.3
  environment:
    DB_HOST: supabase-db
    DB_PORT: "5432"
    DB_DRIVER: postgres
    DB_NAME: postgres
    DB_SSL: allow
    GOTRUE_API_HOST: "0.0.0.0"
    GOTRUE_API_PORT: "9999"
    GOTRUE_SITE_URL: https://supabase-kong-<NAMESPACE>.apps.<GUID>.p1.openshiftapps.com/
    GOTRUE_URI_ALLOW_LIST: "*"
    GOTRUE_DISABLE_SIGNUP: "false"
    GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
    GOTRUE_JWT_ADMIN_ROLES: service_role
    GOTRUE_JWT_AUD: authenticated
    GOTRUE_JWT_EXP: "3600"
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "no-reply@redhat.com"
    GOTRUE_SMTP_HOST: "smtp.example.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "no-reply@redhat.com"
    GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
    GOTRUE_SMS_AUTOCONFIRM: "false"
    GOTRUE_MAILER_URLPATHS_INVITE: "http://localhost:32534/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_CONFIRMATION: "http://localhost:32534/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_RECOVERY: "http://localhost:32534/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: "http://localhost:32534/auth/v1/verify"
    GOTRUE_API_ENDPOINT: "https://supabase-kong-<NAMESPACE>.apps.<GUID>.p1.openshiftapps.com"

rest:
  image:
    repository:  public.ecr.aws/supabase/postgrest
    tag: v12.0.1
  environment:
    DB_HOST: supabase-db
    DB_PORT: "5432"
    DB_DRIVER: postgres
    DB_NAME: postgres
    DB_SSL: allow
    PGRST_DB_SCHEMA: public,storage
    PGRST_DB_ANON_ROLE: anon
    PGRST_DB_USE_LEGACY_GUCS: "false"

realtime:
  image:
    repository:  public.ecr.aws/supabase/realtime
    tag: v2.25.50
  environment:
    DB_HOST: supabase-db
    DB_PORT: "5432"
    DB_NAME: postgres
    DB_SSL: "false"
    PORT: "4000"
    REPLICATION_MODE: RLS
    REPLICATION_POLL_INTERVAL: "100"
    SECURE_CHANNELS: "true"
    SLOT_NAME: supabase_realtime_rls
    TEMPORARY_SLOT: "true"
    DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
    DB_ENC_KEY: supabaserealtime
    FLY_ALLOC_ID: fly123
    FLY_APP_NAME: realtime
    ERL_AFLAGS: -proto_dist inet_tcp
    ENABLE_TAILSCALE: "false"
    DNS_NODES: "''"

meta:
  image:
    repository:  quay.io/jland/postgres-meta
    tag: v0.77.21
  environment:
    DB_HOST: supabase-db
    DB_PORT: "5432"
    DB_DRIVER: postgres
    DB_NAME: postgres
    DB_SSL: disable
    PG_META_PORT: "8080"

storage:
  image:
    repository:  public.ecr.aws/supabase/storage-api
    tag: v0.46.4
  environment:
    DB_HOST: supabase-db
    DB_PORT: "5432"
    DB_DRIVER: postgres
    DB_NAME: postgres
    DB_SSL: disable
    POSTGREST_URL: http://supabase-rest:3000
    PGOPTIONS: -c search_path=storage,public
    FILE_SIZE_LIMIT: '52428800'
    STORAGE_BACKEND: file
    FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    TENANT_ID: stub
    REGION: stub
    GLOBAL_S3_BUCKET: stub
  persistence: 
    enabled: false
    accessModes:
      - ReadWriteOnce
    size: 4Gi
    # Assumed AWS EBS gp3 storage class
    storageClassName: gp3-csi
    annotations:
      helm.sh/resource-policy: "keep"


kong:
  image:
    repository:  public.ecr.aws/supabase/kong
    tag: 2.8.1
  environment:
    KONG_DATABASE: "off"
    KONG_DECLARATIVE_CONFIG: /home/templates/template.yml
    KONG_DNS_ORDER: LAST,A,CNAME
    KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
    KONG_LOG_LEVEL: debug
    DASHBOARD_USERNAME: myusername
    DASHBOARD_PASSWORD: superSecretPassword