apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-role
rules:
- apiGroups: ['security.openshift.io']
  resources: ['securitycontextconstraints']
  verbs:     ['use']
  resourceNames: ['anyuid']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scc-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-role
subjects:
- kind: ServiceAccount
  name: db-service-account